
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    user: "0:0"
    ports:
      - "8989:8989"
    environment:
      - TZ=Asia/Jakarta
      - PGID=0
      - PUID=0
    volumes:
      - $STACK_DIR/data/sonarr:/config:z
      - $MEDIA_PATH:/data:z
      - $MEDIA_PATH/torrents:/downloads:z

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    user: "0:0"
    environment:
      - PGID=0
      - PUID=0
      - TZ=Asia/Jakarta
    volumes:
      - $STACK_DIR/data/prowlarr:/config:z
    network_mode: "container:gluetun"

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    user: "0:0"
    environment:
      - PGID=0
      - TZ=Asia/Jakarta
      - PUID=0
    volumes:
      - $MEDIA_PATH/torrents:/downloads:z
      - $STACK_DIR/data/qbittorrent:/config:z
      - $MEDIA_PATH:/data:z
    network_mode: "container:gluetun"
